### ISSUE TITLE
Love your fork of Konform, but I am missing installation instructions

### ISSUE THREAD

**Issue by dvberkel** [konfork/konfork#1]
Your fork of Konform is lovely, especially the name :fork_and_knife:. But I am missing the installation instructions.

> How should I go about and make use of this lovely library?

**Comment by gmulders** [comment]
Hi @dvberkel,

Thank you for your interest in Konfork!

You are right about the missing installation instructions in the README.md. I have added the instructions. 

Please note that for the first couple of versions, the API will change here and there. Once the API is more stable, I will add a detailed usage and examples.
