### ISSUE TITLE
Missing String predicate validators

### ISSUE THREAD

**Issue by dvberkel** [konfork/konfork#4]
Various predicates on `String` would make ideal validators. Examples include

* `isEmpty`
* `isNotEmpty`.

**Comment by dvberkel** [comment]
I will create a pull-request that adds validators based on `String` predicates to the `konfork-core`.

**Comment by geertmulders** [comment]
Great @dvberkel !

**Comment by dvberkel** [comment]
Pull-request #5 adds these validators
